### ISSUE TITLE
Add support for passwords containing non-ascii data

### ISSUE THREAD

**Issue by lafreak** [KaDw/pk-crypt-rs#1]
-p accepts only ascii characters, some obfuscation use cases require using password bytes from entire range: 0-255

**Comment by KaDw** [comment]
Good catch! -p accepts Unicode but there may be a problem with encoding.

For unzipping I use [zip-rs](https://github.com/zip-rs), it has option to provide password as array of bytes. Rust uses UTF-8 so if you have any special character like `Ä` and convert it to bytes you will get `0xC3 0xA4`. Now the zipping part is done using  `pkzipc.exe` which is an old software and it uses (at least in my case) Windows-1252 encoding. It turns out that it encodes `Ä` as `0xC4` which is totally different.

Since `pkzipc.exe` is always used to create the archive a quick fix might be to just use Windows-1252 encoding also for decryt part, this way it will always match the pkzipc password.

Another solution would be to ship `pkzipc.exe` with the pk-crypt-rs and use it also for unzipping.

**Comment by KaDw** [comment]
@lafreak I went with another idea, now encoding is up to the user, if it's different from UTF-8, you have to convert the text yourself to desired encoding and supply byte representation using `--password-bytes` instead of `password-text` option. Let me know if this works for you. You can find binaries here: [v0.2.0](https://github.com/KaDw/pk-crypt-rs/releases/tag/v0.2.0)

**Comment by KaDw** [comment]
No response means it's working 😃  - closing
